services:
  app:
    image: szuvarska/globaltimesanalysis:latest
    ports:
      - "8000:8000"
    environment:
      - NAME=GlobalTimesAnalysis
    volumes:
      - .:/app
    command: ["shiny", "run", "app.py", "--host", "0.0.0.0", "--port", "8000"]